### ISSUE TITLE
Add new instance of Identity Kit for Nova Scotia

### ISSUE THREAD

**Issue by swcurran** [bcgov/identity-kit-poc#101]
Nova Scotia would like to have it's own instance of the full identity kit - including the admin and issuer web apps.

Please deploy new versions of the apps for Nova Scotia either in the same OpenShift projects or in a separate one. For now, the sites should be identical (albeit with different databases, URLs and associated configurations), but we will make some UI updates for the Nova Scotia instance.  Likewise, use a variation on the current URLs for the deployment, but expect that we will acquire a DNS name for the deployment and use that for the production sites.

I expect that this will be needed within the next three weeks.

**Comment by swcurran** [comment]
Peter - please confirm that this is a go as described above, including the timing. What do you think we should use for the URLs for the site?  I think we should be able to get a DNS name pretty easily for this.

**Comment by swcurran** [comment]
Emiliano, on the DNS name, please coordinate with John to use https://ns-id.vonx.io.

**Comment by esune** [comment]
@jljordan42 following-up to @swcurran comment above. We will need a DNS entry pointing to the OCP for `ns-id.vonx.io`. I will start working on the app deployments using standard pathfinder URLs, please let me know when the DNS entry has been generated so we can finish setting it up and test it.

**Comment by esune** [comment]
App has been deployed and DNS entries activated/enabled.

The current version of the deployed app is exactly the same of the BC Identity Kit (both flow and look-and-feel).

**Comment by swcurran** [comment]
@watkinspd @jljordan42 - please review and add new issues of what you want changed from the Nova Scotia deployment.

Thanks!

**Comment by esune** [comment]
@watkinspd @jljordan42 I will be adding your users as admins shortly, if/when we have other people that require access please ask them to sign-in at https://sso.pathfinder.gov.bc.ca/auth/admin/gzyg46lx/console using GitHub (supposing that is what we want to use) and let me know so I add the admin role to their profile.

**Comment by watkinspd** [comment]
1 - Remove idir if it’s still connected on the keycloak login page
2 - Can the BC Flag be removed from the keycloak login page or are we stuck that that?
3 - Will the issuer work using only github accounts? Can a github account be authorized so it canbe used to make invitations? If so, great!
4 - The text for the credential that is issued as displayed in the personal agent should be NSGov-POC-Issuer
5 - The radio button in the admin console should be NS, or if it’s not needed, just remove it
6 - When user clicks on invitation link and logs in the page that displays with “BC Services Card info” needs to be changed to remove references to BC stuff. If its easy to remove the BC Services Card information box just do that so that you go straight to the part where you enter your data, otherwise change the heading so it says “Github login data” or something along those lines.

**Comment by esune** [comment]
@watkinspd 
1. Already removed, only username/password and GitHub are available now
2. I am using the default keycloak theme. We could eventually design a custom landing page, I am currently looking into updating the app logic (removing login in client app and other tweaks and updates).
3. Currently the login options we have are either GitHub account authentication or "local" registration on Keycloak. The users that need to send out invitations will need to sign-in once to create their user profile in Keycloak and then I can assign the users with admin privileges. Until they login I don't know who they are since on first login a link is created between Keycloak and Github user using a guid.
4. Already setup that way 🙂
5/6. Will incorporate these changes as part of the tweaks/updates I mentioned above

**Comment by watkinspd** [comment]
@esune This is great stuff.
