### ISSUE TITLE
Make the connection invitation in the issuer a URI

### ISSUE THREAD

**Issue by swcurran** [bcgov/identity-kit-poc#128]
Per @sukalpomitra the invitation from the issuer is not a URI - it's just the encoded invitation. That seems to work fine with the Streetcred agent, but is not correct.  Please verify and if that is correct, adjust and verify it still works with Streetcred and with OSMA.

Example URI: `http://iiwbook.vonx.io?c_i=gsgsgsgsg`

What the issuer sends: `gsgsgsgsg`

Where `gsgsgsgsg` is the encoded invitation JSON.

**Comment by esune** [comment]
Link to relevant Aries RFC section: https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#standard-invitation-encoding

**Comment by esune** [comment]
Fixed in #127

**Comment by esune** [comment]
I could successfully go through the issuance process using StreetCred.

With OSMA I am now able to read the invitation and successfully establish a connection, however the flow stops when the issuer sends the credential offer as it appears that it is not received/processed by OSMA.

**Comment by esune** [comment]
@sukalpomitra the above scenario happens when running in localhost using `ngrok`.

I also tried the `identity-kit` deployed to OpenShift:
1. Connection remains in `Negotiating` state
2. A credential offer is received while the connection is still in `Negotiating`
3. Accepting the credential offer updates the credential exchange status to `Requested`
4. The flow seems to get stuck and breaks here

**Comment by sukalpomitra** [comment]
@esune Everything worked for me
<img width="716" alt="Screenshot 2020-02-06 at 11 56 29 AM" src="https://user-images.githubusercontent.com/7150428/73904878-70279700-48d8-11ea-8230-d8b49696f840.png">
<img width="1643" alt="Screenshot 2020-02-06 at 11 59 10 AM" src="https://user-images.githubusercontent.com/7150428/73904880-73bb1e00-48d8-11ea-9777-cefed7e835d2.png">
