### ISSUE TITLE
A simpler "Hello World" app for Verified Person

### ISSUE THREAD

**Issue by watkinspd** [bcgov/identity-kit-poc#71]
We will need a simple "Hello World" service that demonstrates using a verified person credential. For example:

As a user with a verified person credential I want to experience how a digtial service requests my credential, how I receive the notice and authorize/reject providing it, and see that if I provide it, that it is received by the service that requested it.

As a developer I want to have a working code sample that shows the bare minimum that I need to do in order to request and receive a verified person credential so that I can jump-start my effort to create a proof of concept digital service without being bothered by the complexity of issuing credentials, or making a personal agent.

So:
identity-kit-hello.pathfinder.gov.bc.ca 
It makes a request for verified person via the QR code and the clickable button
User scans QR with agent
identity-kit-hello starts runing the progress screen
Request is received
Credential is provided
identity-kit-hello shows that credential is received and shows the data it received
identity-kit-hello.pathfinder.gov.bc.ca shows progress is complete

**Comment by swcurran** [comment]
Peter,

Do you want the authentication to occur behind Keycloak or directly?  We
can do either.

Another thing we might want to experiment with in doing this if this is a
non-Keycloak world. We can use a cookie in the browser so that on returning
to the page, we know who you are and respond accordingly. For example, if
within a given time-window (session) you get in automatically. If longer,
we initiate the credential request process without a QR code - with a "Not
you?" option to bring up the QR code.

Anyway - this is easy and we'll get this posted.  Any thoughts on styling
the site, or what to display once you are "logged in"?

Thanks!

**Comment by watkinspd** [comment]
I suggest without Keycloak - ideally the hello world app will be easy to run by any developer.
I like your idea above for simple cookie browser model.
For UI - it should say something like "Verifiable Credentials Hello World App" and display the data the user supplied in their response to the proof request. Perhaps some links to the code repo and other information sources.

**Comment by swcurran** [comment]
This is done with the work that @esune did to embed an OIDC library into a website so that we didn't have to use Keycloak.  As well, the Law Society demo has been improved. The UI is not such that we want to shout about this, but the work is done and the example is there, easily extended.

Closing this issue.
