### ISSUE TITLE
Issuing using direct registration rather than login service

### ISSUE THREAD

**Issue by watkinspd** [bcgov/identity-kit-poc#83]
As a government that does not have a login service, I need an issuing service that simulates the role of a government employee acting as an identity proofing and registration agent for the verifiable credential so that I can easily participate in the POC.

For example: the gov of x does not have any form of digital ID to leverage for the POC. They need to demonstrate how an authorized person in their organization could directly register a person or the POC and issue them with a POC digital ID for verifiable person.

A suggestion would be to clone identity-kit-admin and change the invitation making screens so that it allows an admin to enter in all of the data needed for a verifiable person credential. The resultant email link for the invitation would simply display the QR code and could be scanned with the agent. The admin is therefore showing the role of a person who is conducting an identity proofing and registration step - albeit for a proof of concept demo issuer.

**Comment by esune** [comment]
@swcurran this sounds like the same as #102 and #105, is this correct?

**Comment by swcurran** [comment]
Yes. And, it adds the other issue that I'm going to add - the special case of the "wa-user" or "wa-admin" user logging into the issuer app.  When that happens, the data from the Admin should be picked up, instead of using the data from the OIDC token. This brings out another "special case".  When there is no OIDC token, use the data about the user that is associated with the time-limited GUID.

That will be yet another issue.  I'll leave you to close/link the issues that you want to use to track the work.

**Comment by esune** [comment]
This has been resolved with the new version of the issuer app.
