### ISSUE TITLE
Update email instructions to match google doc

### ISSUE THREAD

**Issue by watkinspd** [bcgov/identity-kit-poc#87]
I made a few edits to the email instructions.

**Comment by swcurran** [comment]
Instructions updated and should be deployed soon.

Note that the instructions to "close your browser" has been added, but I think it is questionable. First, the "logout" mechanism should be in place shortly, so that after the issue is complete, you are logged out of the session.  That should eliminate the problem entirely. Second, not sure, but I think the token is preserved across browser restarts, so I'm not sure that the restart even helps.

Regardless - please monitor and we'll see if we can eliminate the problem with the forced logout after issuance.

Please close once the email content has been confirmed.
